name: Create and Publish package
on:
  push:
    tags:
      - v*
    branches:
      - DP-paulmar1
jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install and build webpack
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: '16.x'
          always-auth: 'true'
          scope: '@timer2ticket'
      - run: |
          npm ci
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: dist/src

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: run-npm-build
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2


    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - 
      name: Build container image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ghcr.io/timer2ticket/timer2ticket-api/timer2ticket-api:${{ env.RELEASE_VERSION }}
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"    

